# Generated by Django 2.2.6 on 2019-10-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePais', models.CharField(help_text='ingrese su lugar de destino', max_length=200)),
            ],
        ),
    ]
