# Generated by Django 2.2.6 on 2019-11-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cotizacion',
            fields=[
                ('nombre', models.CharField(help_text='ingrese su lugar de destino', max_length=200)),
                ('rut', models.CharField(help_text='ingrese su rut con puntos y guion', max_length=12, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(help_text='escriba su mensaje', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='pais',
        ),
    ]
